/* Normally autogenerated by nano's own build (Makefile.am's "revision.h:"
 * rule, from `git describe` when building from a git checkout, or a
 * "PLAINBUILD" fallback otherwise) - poc-os doesn't run that autotools
 * machinery (see the Makefile's coreutils/ comment), and nano.c only
 * ever uses this file's content behind "#ifdef REVISION", so leaving it
 * empty is exactly equivalent to nano's own tarball-build fallback path.
 */
