// Trap/interrupt dispatch: builds the IDT, then trap() below is the
// single C entry point that trapasm.asm's alltraps calls for every
// exception, hardware interrupt, and int-based system call.

#include "types.h"
#include "defs.h"
#include "param.h"
#include "memlayout.h"
#include "mmu.h"
#include "proc.h"
#include "x86.h"
#include "traps.h"
#include "spinlock.h"

// Interrupt descriptor table (shared by all CPUs).
struct gatedesc idt[256];
// Generated by kernel/vectors.pl into build/obj/kernel/vectors.asm:
// array of 256 entry pointers. uintp, not uint, because vectors.pl's
// output uses 8-byte (dq) entries to hold full 64-bit vectorN
// addresses - a uint-typed array here would read both the wrong width
// and the wrong stride.
extern uintp vectors[];
struct spinlock tickslock;
uint ticks;

void
tvinit(void)
{
  int i;

  // One gate per vector, all as interrupt gates (istrap=0, so the CPU
  // clears IF on entry) at DPL 0, so user code can't invoke them
  // directly with int. T_SYSCALL is the deliberate exception: it's a
  // trap gate (leaves IF alone) at DPL_USER, since that's the one
  // interrupt user programs are supposed to raise themselves.
  for(i = 0; i < 256; i++)
    SETGATE(idt[i], 0, SEG_KCODE<<3, vectors[i], 0);
  SETGATE(idt[T_SYSCALL], 1, SEG_KCODE<<3, vectors[T_SYSCALL], DPL_USER);

  initlock(&tickslock, "time");
}

// Load the IDT register; must run on every CPU (it's per-CPU state, even
// though the table it points at is shared).
void
idtinit(void)
{
  lidt(idt, sizeof(idt));
}

// Diagnostic + kill, shared by T_PGFLT's unresolved-fault path and the
// default: case below - both mean "user process misbehaved", just
// reached from different trap numbers.
static void
baduseraccess(struct trapframe *tf)
{
  // %p (not %x): tf->cs/tf->eip are uintp-width on the 64-bit build
  // (see x86.h's trapframe) - passing them to a %x, which reads a
  // plain 4-byte int/uint, would desync cprintf's va_arg reads for
  // the rest of the format string.
  cprintf("pid %d %s: trap %d err %d on cpu %d "
          "eip 0x%p addr 0x%p sz 0x%p--kill proc\n",
          myproc()->pid, myproc()->name, (int)tf->trapno,
          (int)tf->err, cpuid(), (uintp)tf->eip, (uintp)rcr2(),
          (uintp)myproc()->sz);
  myproc()->killed = 1;
}

//PAGEBREAK: 41
void
trap(struct trapframe *tf)
{
  if(tf->trapno == T_SYSCALL){
    if(myproc()->killed)
      exit();
    myproc()->tf = tf;
    syscall();
    if(myproc()->killed)
      exit();
    goto done;
  }

  switch(tf->trapno){
  case T_IRQ0 + IRQ_TIMER:
    if(cpuid() == 0){
      acquire(&tickslock);
      ticks++;
      wakeup(&ticks);
      release(&tickslock);
    }
    lapiceoi();
    break;
  case T_IRQ0 + IRQ_IDE:
    ideintr();
    lapiceoi();
    break;
  case T_IRQ0 + IRQ_IDE+1:
    // Bochs generates spurious IDE1 interrupts.
    break;
  case T_IRQ0 + IRQ_KBD:
    kbdintr();
    lapiceoi();
    break;
  case T_IRQ0 + IRQ_MOUSE:
    mouseintr();
    lapiceoi();
    break;
  case T_IRQ0 + IRQ_COM1:
    uartintr();
    lapiceoi();
    break;
  case T_IRQ0 + 7:
  case T_IRQ0 + IRQ_SPURIOUS:
    // %p (not %x): tf->cs/tf->eip are uintp-width on the 64-bit build
    // (see x86.h's trapframe) - passing them to a %x, which reads a
    // plain 4-byte int/uint, would desync cprintf's va_arg reads for
    // the rest of the format string.
    cprintf("cpu%d: spurious interrupt at %p:%p\n",
            cpuid(), (uintp)tf->cs, (uintp)tf->eip);
    lapiceoi();
    break;

  case T_PGFLT:
    if(myproc() == 0 || (tf->cs&3) == 0){
      // A page fault in the kernel is still always a real bug here -
      // this kernel has no lazy-mapping/demand-paging path of its own
      // that would ever expect one.
      cprintf("unexpected trap %d from cpu %d eip %p (cr2=0x%p)\n",
              (int)tf->trapno, cpuid(), (uintp)tf->eip, (uintp)rcr2());
      panic("trap");
    }
    // vm_handle_pagefault() (kernel/vm.c) resolves a copy-on-write
    // fault (kernel/vm.c's copyuvm(), from fork()) in place; anything
    // else - a genuine wild pointer, a write to real read-only memory -
    // it declines (-1), and reaches the same kill path as any other
    // unhandled trap below.
    if(vm_handle_pagefault(myproc()->pgdir, (uintp)rcr2()) == 0)
      goto done;
    baduseraccess(tf);
    break;

  //PAGEBREAK: 13
  default:
    if(myproc() == 0 || (tf->cs&3) == 0){
      // In kernel, it must be our mistake.
      cprintf("unexpected trap %d from cpu %d eip %p (cr2=0x%p)\n",
              (int)tf->trapno, cpuid(), (uintp)tf->eip, (uintp)rcr2());
      panic("trap");
    }
    // In user space, assume process misbehaved. sz (added during the
    // GUI roadmap ToaruOS-style rewrite's terminal.c debugging) shows
    // whether a faulting addr sits just past the process's own mapped
    // top (a real overflow) or is a wildly out-of-range pointer -
    // meaningfully narrows down userspace crashes without a debugger.
    baduseraccess(tf);
  }

  // Force process exit if it has been killed and is in user space.
  // (If it is still executing in the kernel, let it keep running
  // until it gets to the regular system call return.)
  if(myproc() && myproc()->killed && (tf->cs&3) == DPL_USER)
    exit();

  // Force process to give up CPU on clock tick.
  // If interrupts were on while locks held, would need to check nlock.
  if(myproc() && myproc()->state == RUNNING &&
     tf->trapno == T_IRQ0+IRQ_TIMER)
    yield();

  // Check if the process has been killed since we yielded
  if(myproc() && myproc()->killed && (tf->cs&3) == DPL_USER)
    exit();

 done:
  // Reassert this process's %fs base right before it actually resumes
  // in user mode. Needed on every return, not just when tls_base last
  // changed: MSR_FS_BASE is CPU state, not part of what swtch() saves/
  // restores per-process, so any context switch since the last time
  // this process ran (a timer tick above via yield(), or another
  // process entirely on this CPU) may have overwritten it with a
  // different process's value. The T_SYSCALL branch above jumps
  // straight here, since a syscall - arch_prctl in particular - is
  // exactly the case where tls_base can change and the very next
  // instruction executed in user mode needs to already see it.
  if(myproc())
    wrmsr(MSR_FS_BASE, myproc()->tls_base);
}
