#!/usr/bin/perl -w

# Generate vectors.asm, the trap/interrupt entry points (NASM syntax).
# There has to be one entry point per interrupt number
# since otherwise there's no way for trap() to discover
# the interrupt number.

print "; generated by vectors.pl - do not edit\n";
print "BITS 32\n";
print "; handlers\n";
print "section .text\n";
print "extern alltraps\n";
for(my $i = 0; $i < 256; $i++){
    print "global vector$i\n";
    print "vector$i:\n";
    if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
        print "  push 0\n";
    }
    print "  push $i\n";
    print "  jmp alltraps\n";
}

print "\n; vector table\n";
print "section .data\n";
print "global vectors\n";
print "vectors:\n";
for(my $i = 0; $i < 256; $i++){
    print "  dd vector$i\n";
}

# sample output:
#   ; handlers
#   section .text
#   global alltraps
#   global vector0
#   vector0:
#     push 0
#     push 0
#     jmp alltraps
#   ...
#
#   ; vector table
#   section .data
#   global vectors
#   vectors:
#     dd vector0
#     dd vector1
#     dd vector2
#   ...
