#!/usr/bin/perl -w

# Generate vectors.asm, the trap/interrupt entry points (NASM syntax).
# There has to be one entry point per interrupt number
# since otherwise there's no way for trap() to discover
# the interrupt number.
#
# Takes the target bit width (32 or 64, default 32) as $ARGV[0] - see
# the Makefile's vectors.asm rule, which passes $(ARCH). The per-vector
# push sequence is identical either way (push a 0 placeholder errcode
# for vectors the CPU doesn't supply one for, then the vector number,
# then jump to the shared handler) since PUSH is 64-bit-operand-sized by
# default in long mode regardless - only the BITS directive and the
# vector table's pointer width (dd vs dq) actually differ.

my $bits = (defined $ARGV[0] && $ARGV[0] eq "64") ? 64 : 32;

print "; generated by vectors.pl - do not edit\n";
print "BITS $bits\n";
print "; handlers\n";
print "section .text\n";
print "extern alltraps\n";
for(my $i = 0; $i < 256; $i++){
    print "global vector$i\n";
    print "vector$i:\n";
    if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
        print "  push 0\n";
    }
    print "  push $i\n";
    print "  jmp alltraps\n";
}

print "\n; vector table\n";
print "section .data\n";
print "global vectors\n";
print "vectors:\n";
my $ptr = ($bits == 64) ? "dq" : "dd";
for(my $i = 0; $i < 256; $i++){
    print "  $ptr vector$i\n";
}

# sample output:
#   ; handlers
#   section .text
#   global alltraps
#   global vector0
#   vector0:
#     push 0
#     push 0
#     jmp alltraps
#   ...
#
#   ; vector table
#   section .data
#   global vectors
#   vectors:
#     dd vector0
#     dd vector1
#     dd vector2
#   ...
