// Wires in gui/font8x16.h (generated by tools/genfont.py, GUI roadmap
// phase 5's font asset - committed since but never actually rendered
// by anything until now).
#include "gfx.h"
#include "../font8x16.h"

void
gfx_draw_glyph(struct gfx_surface *s, int x, int y, char ch, unsigned int color)
{
  const unsigned char *rows;
  unsigned int px;
  int row, col;

  if (ch < 32 || ch > 126)
    return;
  rows = font8x16[(unsigned char)ch - 32];
  px = gfx_pack(s, color);

  for (row = 0; row < FONT_CELL_H; row++) {
    unsigned char bits = rows[row];

    for (col = 0; col < FONT_CELL_W; col++) {
      if (bits & (0x80 >> col)) {
        int px_x = x + col, px_y = y + row;

        if (px_x >= 0 && px_x < (int)s->w && px_y >= 0 && px_y < (int)s->h)
          *(unsigned int *)(s->pixels + (unsigned long)px_y * s->pitch + (unsigned long)px_x * 4) = px;
      }
    }
  }
}

void
gfx_draw_string(struct gfx_surface *s, int x, int y, const char *str, unsigned int color)
{
  int cx = x;

  for (; *str; str++) {
    gfx_draw_glyph(s, cx, y, *str, color);
    cx += FONT_CELL_W;
  }
}
