/* Hand-generated for poc-os/musl (x86_64), replacing bash's normal
 * mksignames-at-build-time step (see support/mksignames.c/signames.c).
 * poc-os's cross build has no target-code-execution step available at
 * build time, so this can't be generated by running a target binary the
 * way a native build normally would - this is the same table
 * support/signames.c's initialize_signames() would build, computed by
 * hand from musl/arch/x86_64/bits/signal.h's real SIGHUP..SIGSYS
 * (1..31, _NSIG 65) and the standard glibc/musl real-time signal
 * convention (SIGRTMIN=34, SIGRTMAX=64, reserving 32/33 for
 * musl's internal thread use - the same reservation glibc makes, hence
 * "SIGJUNK" for those two: musl's <signal.h> has no public SIGxxx name
 * for them, matching how a real Linux/glibc `kill -l` output looks). */
char *signal_names[NSIG + 4] = {
    "EXIT",
    "SIGHUP",
    "SIGINT",
    "SIGQUIT",
    "SIGILL",
    "SIGTRAP",
    "SIGABRT",
    "SIGBUS",
    "SIGFPE",
    "SIGKILL",
    "SIGUSR1",
    "SIGSEGV",
    "SIGUSR2",
    "SIGPIPE",
    "SIGALRM",
    "SIGTERM",
    "SIGSTKFLT",
    "SIGCHLD",
    "SIGCONT",
    "SIGSTOP",
    "SIGTSTP",
    "SIGTTIN",
    "SIGTTOU",
    "SIGURG",
    "SIGXCPU",
    "SIGXFSZ",
    "SIGVTALRM",
    "SIGPROF",
    "SIGWINCH",
    "SIGIO",
    "SIGPWR",
    "SIGSYS",
    "SIGJUNK(32)",
    "SIGJUNK(33)",
    "SIGRTMIN",
    "SIGRTMIN+1",
    "SIGRTMIN+2",
    "SIGRTMIN+3",
    "SIGRTMIN+4",
    "SIGRTMIN+5",
    "SIGRTMIN+6",
    "SIGRTMIN+7",
    "SIGRTMIN+8",
    "SIGRTMIN+9",
    "SIGRTMIN+10",
    "SIGRTMIN+11",
    "SIGRTMIN+12",
    "SIGRTMIN+13",
    "SIGRTMIN+14",
    "SIGRTMIN+15",
    "SIGRTMAX-14",
    "SIGRTMAX-13",
    "SIGRTMAX-12",
    "SIGRTMAX-11",
    "SIGRTMAX-10",
    "SIGRTMAX-9",
    "SIGRTMAX-8",
    "SIGRTMAX-7",
    "SIGRTMAX-6",
    "SIGRTMAX-5",
    "SIGRTMAX-4",
    "SIGRTMAX-3",
    "SIGRTMAX-2",
    "SIGRTMAX-1",
    "SIGRTMAX",
    "DEBUG",
    "ERR",
    "RETURN",
    (char *)0x0
};

#define initialize_signames()
