#!/bin/sh
# Regenerates arch/x86_64/bits/syscall.h.in from poc-os's own syscall
# table (../../include/syscall.h), the single source of truth for SYS_
# numbers. Run this after adding a syscall to the kernel and re-run the
# musl build - musl's own Makefile then derives SYS_x aliases from the
# __NR_x names this produces (see its `obj/include/bits/syscall.h` rule).
#
# poc-os is a from-scratch syscall ABI, not Linux's, so unlike a normal
# musl arch port this file has no relation to Linux's __NR_ numbering -
# it just mirrors whatever include/syscall.h currently defines.
set -e
cd "$(dirname "$0")/.."
POC_SYSCALL_H=../include/syscall.h
OUT=arch/x86_64/bits/syscall.h.in

{
	echo "/* Generated by tools/gen-poc-syscall.sh from $POC_SYSCALL_H. Do not edit by hand. */"
	sed -n 's/^#define SYS_/#define __NR_/p' "$POC_SYSCALL_H"
} > "$OUT"
