/*
 * pipesize.h
 *
 * Normally generated by psize.sh, which measures the *host's* real pipe
 * buffer size by writing to an actual pipe until it blocks - not
 * meaningful when cross-compiling (there's no target to run that probe
 * on). Set by hand instead, to poc-os's own real, fixed pipe buffer size
 * (kernel/pipe.c's own PIPESIZE, 512 bytes - not a guess: it's the exact
 * capacity of the ring buffer sys_pipe()-backed processes actually
 * block on, so a caller of `ulimit -p` (in 512-byte units, see
 * ulimit.def) sees the real, correct answer for this kernel).
 */

#define PIPESIZE 512
