#!/usr/bin/env python3
# Generates gui/font8x16.h - an 8x16 1-bit bitmap font for printable
# ASCII (32-126), rasterized from a real macOS system monospace font
# (Menlo) rather than hand-transcribed or fetched from an unverifiable
# source - see the GUI roadmap phase 6 plan doc's own Context section
# for why (a public-domain glyph table couldn't be safely sourced this
# session without risking silent pixel-data transcription errors).
# Host-side tool only - not part of the poc-os build itself, and the
# generated header is committed so building poc-os never needs Python/
# PIL. Re-run this and commit the result if the font ever needs to
# change.
#
# Usage: python3 tools/genfont.py
from PIL import Image, ImageDraw, ImageFont

CELL_W, CELL_H = 8, 16
FONT_PATH = "/System/Library/Fonts/Menlo.ttc"
FONT_SIZE = 14
Y_OFFSET = -1

font = ImageFont.truetype(FONT_PATH, FONT_SIZE)

rows = []
for code in range(32, 127):
    ch = chr(code)
    img = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(img)
    d.text((0, Y_OFFSET), ch, font=font, fill=255)
    px = img.load()
    glyph_rows = []
    for y in range(CELL_H):
        byte = 0
        for x in range(CELL_W):
            if px[x, y] >= 128:
                byte |= 0x80 >> x
        glyph_rows.append(byte)
    rows.append((code, ch, glyph_rows))

with open("gui/font8x16.h", "w") as f:
    f.write("// Generated by tools/genfont.py from %s (size %d) - do not\n"
            "// edit by hand, re-run the generator instead. Covers printable\n"
            "// ASCII 32 (space) through 126 (~); index with ch - 32.\n"
            "// One row-major byte per pixel row, MSB = leftmost pixel.\n"
            % (FONT_PATH, FONT_SIZE))
    f.write("#define FONT_CELL_W %d\n#define FONT_CELL_H %d\n\n" % (CELL_W, CELL_H))
    f.write("static const unsigned char font8x16[95][16] = {\n")
    for code, ch, glyph_rows in rows:
        comment = ch if ch not in ("\\", "'") else ("\\\\" if ch == "\\" else "\\'")
        f.write("  { " + ", ".join("0x%02x" % b for b in glyph_rows) + " }, // %3d '%s'\n"
                % (code, comment))
    f.write("};\n")

print("wrote gui/font8x16.h (%d glyphs)" % len(rows))
